version: "2.4"

services:
  adminer:
    image: adminer:4.7
    restart: always
    restart: always
    ports:
    - 127.0.0.1:18080:8080/tcp

  postgres:
    image: postgres:9.6
    restart: always
    volumes:
    - ./storage/pgdata:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: dns_manager
      POSTGRES_PASSWORD: passw0rd
    ports:
    - 127.0.0.1:15432:5432/tcp

  powerdns:
    build: ./images/powerdns
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: passw0rd
      DB_NAME: dns_manager
    ports:
    - 10053:53/tcp
    - 10053:53/udp
    - 18081:8081/tcp

  dns-manager:
    build: .
    ports:
    - 127.0.0.1:13000:3000/tcp
